### ISSUE TITLE
IOError: No such file or directory: 'data/review/word2id.p'

### ISSUE THREAD

**Issue by allsto** [egrcc/Review-Response-Generation#2]
Hi!
As I try to run the train.py script I receive this error pretty much in the beginning of the script (line 38 of the train.py):
IOError: [Errno 2] No such file or directory: 'data/review/word2id.p'
But since the embeddings are only supposed to be produced during training, I do not understand where this issue comes from.
I already tried to run the script from different directories and added the data and review directories to the main directory manually.

**Comment by joshchang0111** [comment]
Hi, I am also facing this error, and have no idea how to solve it.
I wonder if you had solved this problem already, 
FileNotFoundError: [Errno 2] No such file or directory: 'data/review/word2id.p'

**Comment by allsto** [comment]
Hi
This is because the vocabulary is not initialized anywhere. You need to add the following lines into the train.py script
utils_data.bulid_vocab("review", 15000) # Word embeddings, where 15000 is the vocab size
utils_data.bulid_field_vocab("review")  # Field embeddings of field names
utils_data.bulid_pos_vocab("review")    # Position embeddings of the _pos1 and _pos2 files
I hope that helps.

**Comment by joshchang0111** [comment]
Hi, I've added these lines and this works well, Thanks a lot!
